<#
.SYNOPSIS
    Category 1 (uncovered endpoints) and category 2 (parameter gaps) of the API drift
    report. Dot-sourced by tools/Build-PfbApiDriftReport.ps1 and its Pester tests.
    Category 3 (ValidateSet drift) lives here too -- see Get-PfbValidateSetDrift, added
    in a later task -- reusing Resolve-PfbFieldValueEnum from
    tools/lib/PfbValueEnumTools.ps1. Category 4 (new ValidateSet candidates) needs no new
    code at all: it's tools/Build-PfbFieldCmdletMap.ps1's existing 'matched' output,
    consumed directly by the orchestrator.
#>

# Deliberately NOT Set-StrictMode -- same reasoning as PfbSpecTools.ps1/PfbValueEnumTools.ps1.

# Endpoints reached exclusively through hand-written auth code that never calls
# Invoke-PfbApiRequest (it's what establishes the session Invoke-PfbApiRequest itself
# depends on) -- confirmed by reading Public/Connection/Connect-PfbArray.ps1,
# Public/Connection/Disconnect-PfbArray.ps1, and Private/Invoke-PfbOAuth2Login.ps1
# directly. admins/api-tokens is deliberately NOT here: Connect-PfbArray.ps1 also touches
# it via raw Invoke-RestMethod for post-login token minting, but GET/POST/DELETE
# admins/api-tokens are already covered through the standard Invoke-PfbApiRequest
# convention by Public/Admin/{Get,New,Remove}-PfbApiToken.ps1, so Get-PfbModuleCalledEndpoints's
# normal scan already sees them without needing this allowlist.
$script:PfbBespokeAuthEndpoints = @(
    'GET /api/api_version',
    'POST /api/login',
    'POST /api/logout',
    'POST /oauth2/1.0/token'
)

# Fields never worth reporting as a category-2 gap, each for its own confirmed reason --
# not the same list as $script:PfbBespokeAuthEndpoints (that's endpoint keys; this is
# field names). Deliberately excludes context_names/allow_errors/sort/total_only -- those
# change request *behavior* (fleet-context targeting, bulk-error tolerance, sorting,
# aggregate-only responses) and are real, if broad, gaps, not noise.
#   - X-Request-ID: no functional effect on the request -- request/response-log
#     correlation only ("Supplied by client during request or generated by server," per
#     the spec), present on 629/632 capability-map endpoints as of 2.27 with zero cmdlets
#     exposing it anywhere (confirmed via grep of Public/+Private/).
#   - continuation_token: superseded by Invoke-PfbApiRequest's own -AutoPaginate, which
#     already reads response.continuation_token and re-queries automatically
#     (Private/Invoke-PfbApiRequest.ps1) -- a typed parameter would let a caller interfere
#     with pagination state the wrapper already owns end-to-end.
#   - offset: an alternate, unused positioning mechanism into the same paginated
#     collections -AutoPaginate already retrieves in full; co-occurs with
#     continuation_token on 208/212 of its capability-map endpoints, and zero cmdlets
#     expose it.
$script:PfbNonActionableParameters = @(
    'X-Request-ID',
    'continuation_token',
    'offset'
)

. (Join-Path $PSScriptRoot 'PfbValueEnumTools.ps1')

function Test-PfbApiVersionNewerThan {
    <#
    .SYNOPSIS
        Tests whether REST version string -Version is numerically newer than -Baseline.
        Naive string comparison ranks '2.9' above '2.26' -- splits each into Major/Minor
        integers instead (same idiom as Get-PfbValueEnumHistory in PfbValueEnumTools.ps1).
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string]$Version,
        [Parameter(Mandatory)] [string]$Baseline
    )

    $vParts = $Version -split '\.'
    $bParts = $Baseline -split '\.'
    $vMajor = [int]$vParts[0]; $vMinor = [int]$vParts[1]
    $bMajor = [int]$bParts[0]; $bMinor = [int]$bParts[1]

    if ($vMajor -ne $bMajor) { return $vMajor -gt $bMajor }
    return $vMinor -gt $bMinor
}

function Get-PfbModuleCalledEndpoints {
    <#
    .SYNOPSIS
        Scans every Public/*.ps1 and Private/*.ps1 function for Invoke-PfbApiRequest
        calls, extracting each literal -Method/-Endpoint pair, normalized to the same
        "<METHOD> /<endpoint>" key format Data/PfbCapabilityMap.json uses (see
        Private/Assert-PfbApiCapability.ps1:40-41).
    .OUTPUTS
        [PSCustomObject]@{ Key; Method; Endpoint; Resolved; Cmdlet; File }[] -- Resolved
        is $false (Key/Method/Endpoint all $null) when a call's -Endpoint isn't a plain
        string literal (built dynamically via interpolation or a variable), never
        silently dropped or guessed at.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string]$PublicDirectory,
        [Parameter(Mandatory)] [string]$PrivateDirectory
    )

    $results = [System.Collections.Generic.List[object]]::new()
    $files = @(Get-ChildItem -Path $PublicDirectory -Filter '*.ps1' -Recurse -File) +
             @(Get-ChildItem -Path $PrivateDirectory -Filter '*.ps1' -Recurse -File)

    foreach ($file in $files) {
        $tokens = $null; $parseErrors = $null
        $ast = [System.Management.Automation.Language.Parser]::ParseFile($file.FullName, [ref]$tokens, [ref]$parseErrors)
        $functionAsts = $ast.FindAll({ param($n) $n -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $true)

        foreach ($funcAst in $functionAsts) {
            $commands = $funcAst.FindAll({
                param($n)
                $n -is [System.Management.Automation.Language.CommandAst] -and
                $n.GetCommandName() -eq 'Invoke-PfbApiRequest'
            }, $true)

            foreach ($cmd in $commands) {
                $method = $null; $endpoint = $null
                $elements = $cmd.CommandElements
                for ($i = 0; $i -lt $elements.Count; $i++) {
                    $el = $elements[$i]
                    if ($el -isnot [System.Management.Automation.Language.CommandParameterAst]) { continue }
                    $next = if ($i + 1 -lt $elements.Count) { $elements[$i + 1] } else { $null }
                    if (-not $next) { continue }
                    if ($el.ParameterName -eq 'Method' -and $next -is [System.Management.Automation.Language.StringConstantExpressionAst]) {
                        $method = $next.Value
                    }
                    elseif ($el.ParameterName -eq 'Endpoint' -and $next -is [System.Management.Automation.Language.StringConstantExpressionAst]) {
                        $endpoint = $next.Value
                    }
                }

                if ($method -and $endpoint) {
                    $normalizedEndpoint = '/' + $endpoint.TrimStart('/')
                    $results.Add([PSCustomObject]@{
                        Key      = "$($method.ToUpperInvariant()) $normalizedEndpoint"
                        Method   = $method.ToUpperInvariant()
                        Endpoint = $normalizedEndpoint
                        Resolved = $true
                        Cmdlet   = $funcAst.Name
                        File     = $file.FullName
                    })
                }
                else {
                    $results.Add([PSCustomObject]@{
                        Key      = $null
                        Method   = $null
                        Endpoint = $null
                        Resolved = $false
                        Cmdlet   = $funcAst.Name
                        File     = $file.FullName
                    })
                }
            }
        }
    }

    return $results
}

function Get-PfbEndpointCoverageGaps {
    <#
    .SYNOPSIS
        Category 1: every Data/PfbCapabilityMap.json endpoint key that no
        Get-PfbModuleCalledEndpoints result covers and that isn't on -BespokeAllowlist.
    .PARAMETER SinceVersion
        When given, only endpoints whose minVersion is strictly newer than this REST
        version are returned -- e.g. -SinceVersion '2.26' isolates gaps introduced by
        2.27 only, dropping the rest of the accumulated backlog.
    .OUTPUTS
        [PSCustomObject]@{ Endpoint; MinVersion }[]
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] $CapabilityMap,
        [Parameter(Mandatory)] [object[]]$CalledEndpoints,
        [string[]]$BespokeAllowlist = @(),
        [string]$SinceVersion
    )

    $calledKeys = [System.Collections.Generic.HashSet[string]]::new([string[]]@(
        $CalledEndpoints | Where-Object { $_.Resolved } | ForEach-Object { $_.Key }
    ))

    foreach ($key in $CapabilityMap.endpoints.PSObject.Properties.Name) {
        if ($calledKeys.Contains($key)) { continue }
        if ($BespokeAllowlist -contains $key) { continue }
        $minVersion = $CapabilityMap.endpoints.$key.minVersion
        if ($SinceVersion -and -not (Test-PfbApiVersionNewerThan -Version $minVersion -Baseline $SinceVersion)) { continue }
        [PSCustomObject]@{
            Endpoint   = $key
            MinVersion = $minVersion
        }
    }
}

function Get-PfbParameterCoverageGaps {
    <#
    .SYNOPSIS
        Category 2: for each endpoint an existing cmdlet already calls, flags a
        capability-map-known parameter/body-field the cmdlet doesn't expose as a typed
        parameter -- but ONLY for "fully mapped" cmdlets (every Public/ parameter on
        every cmdlet calling this endpoint resolved Surface -eq 'Typed'; zero
        AttributesOnly/TypedUnresolved anywhere). A cmdlet with any AttributesOnly/
        TypedUnresolved parameter may already expose a "new" field through a path this
        AST-only inventory can't see, so its endpoint gets a not-verified entry instead
        of a guessed gap.
    .PARAMETER SinceVersion
        When given, a gap's MissingParameters is filtered down to only fields whose
        capability-map version is strictly newer than this REST version -- e.g.
        -SinceVersion '2.26' isolates fields introduced by 2.27 only. An endpoint whose
        every missing field predates -SinceVersion is dropped from ParameterGaps
        entirely (not emitted with an empty MissingParameters list).
    .PARAMETER ExcludedFields
        Field names never reported as a missing parameter, regardless of version --
        e.g. $script:PfbNonActionableParameters. For fields with no functional gap worth
        reporting (request-tracing headers, pagination internals already handled by
        -AutoPaginate, etc.) that would otherwise appear on nearly every gap and drown out
        real ones. An endpoint whose every missing field is excluded is dropped from
        ParameterGaps entirely (not emitted with an empty MissingParameters list).
    .OUTPUTS
        [PSCustomObject]@{ ParameterGaps; NotVerified }. ParameterGaps is
        [PSCustomObject]@{ Endpoint; Cmdlets; MissingParameters }[]. NotVerified is
        [PSCustomObject]@{ Endpoint; Cmdlets; Reason }[].
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] $CapabilityMap,
        [Parameter(Mandatory)] [object[]]$CmdletInventory,
        [Parameter(Mandatory)] [object[]]$CalledEndpoints,
        [string]$SinceVersion,
        [string[]]$ExcludedFields = @()
    )

    $inventoryByCmdlet = $CmdletInventory | Group-Object -Property Cmdlet -AsHashTable -AsString
    $endpointGroups = @($CalledEndpoints | Where-Object { $_.Resolved } | Group-Object -Property Key)

    $parameterGaps = [System.Collections.Generic.List[object]]::new()
    $notVerified = [System.Collections.Generic.List[object]]::new()

    foreach ($group in $endpointGroups) {
        $key = $group.Name
        $entry = $CapabilityMap.endpoints.$key
        if (-not $entry) { continue }

        $cmdlets = @($group.Group.Cmdlet | Select-Object -Unique)

        $fullyMapped = $true
        $exposedWireNames = [System.Collections.Generic.HashSet[string]]::new()
        foreach ($cmdletName in $cmdlets) {
            $rows = @($inventoryByCmdlet[$cmdletName])
            foreach ($row in $rows) {
                if ($row.Surface -ne 'Typed') { $fullyMapped = $false; continue }
                if ($row.WireName) { [void]$exposedWireNames.Add($row.WireName) }
            }
        }

        if (-not $fullyMapped) {
            $notVerified.Add([PSCustomObject]@{ Endpoint = $key; Cmdlets = $cmdlets; Reason = 'has attributes/unresolved surface' })
            continue
        }

        $fieldVersions = @{}
        if ($entry.parameters) { foreach ($p in $entry.parameters.PSObject.Properties) { $fieldVersions[$p.Name] = $p.Value } }
        if ($entry.bodyProperties) { foreach ($p in $entry.bodyProperties.PSObject.Properties) { $fieldVersions[$p.Name] = $p.Value } }

        $knownFieldNames = [System.Collections.Generic.List[string]]::new()
        $knownFieldNames.AddRange([string[]]@($fieldVersions.Keys))

        # Sort-Object here is load-bearing, not cosmetic: $fieldVersions above is a plain
        # Hashtable, whose .Keys enumeration order depends on .NET's per-process-randomized
        # string hash codes -- without this sort, MissingParameters silently reorders itself
        # run-to-run on identical input (confirmed live: regenerating the drift report twice
        # produced two byte-different files for the same underlying content).
        $missing = @($knownFieldNames | Select-Object -Unique | Where-Object { -not $exposedWireNames.Contains($_) } | Sort-Object)
        if ($SinceVersion) {
            $missing = @($missing | Where-Object { Test-PfbApiVersionNewerThan -Version $fieldVersions[$_] -Baseline $SinceVersion })
        }
        if ($ExcludedFields) {
            $missing = @($missing | Where-Object { $ExcludedFields -notcontains $_ })
        }
        if ($missing.Count -gt 0) {
            $parameterGaps.Add([PSCustomObject]@{ Endpoint = $key; Cmdlets = $cmdlets; MissingParameters = $missing })
        }
    }

    return [PSCustomObject]@{ ParameterGaps = $parameterGaps.ToArray(); NotVerified = $notVerified.ToArray() }
}

function Get-PfbValidateSetDrift {
    <#
    .SYNOPSIS
        Category 3: flags a typed Public/ parameter whose hand-written ValidateSet
        disagrees with the spec's current documented value list for the same field --
        missing values (the spec documents a legal value the ValidateSet rejects
        client-side, e.g. the real Get-PfbArrayPerformance -Protocol 'all' bug),
        stale values (the ValidateSet allows a value the spec no longer, or never did,
        document), or both.
    .OUTPUTS
        [PSCustomObject]@{ Cmdlet; Parameter; CurrentValidateSet; SpecValues;
        MissingValues; StaleValues }[] -- only for parameters whose wire name resolves
        to exactly one spec value-enum record ('matched' via Resolve-PfbFieldValueEnum);
        a HasValidateSet parameter that resolves to 'collision'/'not-found-in-resource'/
        'no-spec-enum-found' is silently excluded (not enough signal to compare against).
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [object[]]$CmdletInventory,
        [Parameter(Mandatory)] $History,
        [Parameter(Mandatory)] [string]$OldestVersion
    )

    $withValidateSet = @($CmdletInventory | Where-Object { $_.Surface -eq 'Typed' -and $_.HasValidateSet })

    foreach ($cand in $withValidateSet) {
        $hint = Get-PfbResourceHint -CmdletName $cand.Cmdlet
        $resolution = Resolve-PfbFieldValueEnum -WireName $cand.WireName -ResourceHint $hint -Endpoint $cand.Endpoint -Method $cand.Method -History $History -OldestVersion $OldestVersion
        if ($resolution.Status -ne 'matched') { continue }

        $current = @($cand.ValidateSetValues)
        $spec = @($resolution.SpecValues)
        $missing = @($spec | Where-Object { $current -notcontains $_ })
        $stale = @($current | Where-Object { $spec -notcontains $_ })

        if ($missing.Count -eq 0 -and $stale.Count -eq 0) { continue }

        [PSCustomObject]@{
            Cmdlet             = $cand.Cmdlet
            Parameter          = $cand.Parameter
            CurrentValidateSet = $current
            SpecValues         = $spec
            MissingValues      = $missing
            StaleValues        = $stale
        }
    }
}
