@{
    RootModule        = 'PureStorageFlashBladePowerShell.psm1'
    ModuleVersion     = '2.0.4'
    GUID              = 'b25473b3-9eb7-414d-8da1-264e10f73d86'
    Author            = 'Pure Storage, Inc.'
    CompanyName       = 'Pure Storage, Inc.'
    Copyright         = '(c) 2026 Pure Storage, Inc. All rights reserved.'
    # See CHANGELOG.md for a complete diff.
    Description       = 'Pure Storage FlashBlade REST 2.x PowerShell Toolkit. Provides comprehensive coverage of FlashBlade REST API 2.x endpoints with a Connect-PfbArray experience that mirrors the FlashArray PureStoragePowerShellSDK2 module. Supports API token, username/password (native REST 2.x /api/login), PSCredential, and certificate-based authentication.'
    PowerShellVersion = '5.1'

    FunctionsToExport = @(
        'Clear-PfbCredential',
        'Connect-PfbArray',
        'Disconnect-PfbArray',
        'Get-PfbCredential',
        'Get-PfbActiveDirectory',
        'Get-PfbAdmin',
        'Get-PfbAdminCache',
        'Get-PfbAdminManagementAccessPolicy',
        'Get-PfbAdminSetting',
        'Get-PfbAdminSshCaPolicy',
        'Get-PfbAlert',
        'Get-PfbAlertWatcher',
        'Get-PfbApiClient',
        'Get-PfbApiToken',
        'Get-PfbApiVersion',
        'Get-PfbArray',
        'Get-PfbArrayClientPerformance',
        'Get-PfbArrayClientS3Performance',
        'Get-PfbArrayConnection',
        'Get-PfbArrayConnectionKey',
        'Get-PfbArrayConnectionPath',
        'Get-PfbArrayConnectionPerformanceReplication',
        'Get-PfbArrayErasure',
        'Get-PfbArrayEula',
        'Get-PfbArrayFactoryResetToken',
        'Get-PfbArrayHttpPerformance',
        'Get-PfbArrayNfsPerformance',
        'Get-PfbArrayPerformance',
        'Get-PfbArrayPerformanceReplication',
        'Get-PfbArrayS3Performance',
        'Get-PfbArraySpace',
        'Get-PfbArraySshCaPolicy',
        'Get-PfbArrayStorageClass',
        'Get-PfbArraySupportedTimeZone',
        'Get-PfbAsyncLog',
        'Get-PfbAsyncLogDownload',
        'Get-PfbAudit',
        'Get-PfbAuditFileSystemPolicy',
        'Get-PfbAuditFileSystemPolicyMember',
        'Get-PfbAuditFileSystemPolicyOperation',
        'Get-PfbAuditObjectStorePolicy',
        'Get-PfbAuditObjectStorePolicyMember',
        'Get-PfbBlade',
        'Get-PfbBucket',
        'Get-PfbBucketAccessPolicy',
        'Get-PfbBucketAccessPolicyRule',
        'Get-PfbBucketAuditFilter',
        'Get-PfbBucketAuditFilterAction',
        'Get-PfbBucketCorsPolicy',
        'Get-PfbBucketCorsPolicyRule',
        'Get-PfbBucketPerformance',
        'Get-PfbBucketReplicaLink',
        'Get-PfbBucketS3Performance',
        'Get-PfbCertificate',
        'Get-PfbCertificateCertificateGroup',
        'Get-PfbCertificateGroup',
        'Get-PfbCertificateGroupCertificate',
        'Get-PfbCertificateGroupUse',
        'Get-PfbCertificateUse',
        'Get-PfbConnection',
        'Get-PfbDirectoryService',
        'Get-PfbDirectoryServiceRole',
        'Get-PfbDirectoryServiceRoleManagementPolicy',
        'Get-PfbDns',
        'Get-PfbDrive',
        'Get-PfbFileLock',
        'Get-PfbFileLockClient',
        'Get-PfbFileSystem',
        'Get-PfbFileSystemAuditPolicy',
        'Get-PfbFileSystemExport',
        'Get-PfbFileSystemGroupPerformance',
        'Get-PfbFileSystemPolicy',
        'Get-PfbFileSystemReplicaLink',
        'Get-PfbFileSystemReplicaLinkPolicy',
        'Get-PfbFileSystemReplicaLinkTransfer',
        'Get-PfbFileSystemSession',
        'Get-PfbFileSystemSnapshot',
        'Get-PfbFileSystemSnapshotPolicy',
        'Get-PfbFileSystemSnapshotTransfer',
        'Get-PfbFileSystemStorageClass',
        'Get-PfbFileSystemUserPerformance',
        'Get-PfbFileSystemWormPolicy',
        'Get-PfbFleet',
        'Get-PfbFleetKey',
        'Get-PfbFleetMember',
        'Get-PfbHardware',
        'Get-PfbHardwareConnector',
        'Get-PfbHardwareConnectorPerformance',
        'Get-PfbHardwareTemperature',
        'Get-PfbKeytab',
        'Get-PfbKeytabDownload',
        'Get-PfbKmip',
        'Get-PfbLag',
        'Get-PfbLegalHold',
        'Get-PfbLegalHoldEntity',
        'Get-PfbLifecycleRule',
        'Get-PfbLog',
        'Get-PfbLogTargetFileSystem',
        'Get-PfbLogTargetObjectStore',
        'Get-PfbMaintenanceWindow',
        'Get-PfbManagementAccessPolicy',
        'Get-PfbManagementAccessPolicyAdmin',
        'Get-PfbManagementAccessPolicyDirectoryRole',
        'Get-PfbManagementAccessPolicyMember',
        'Get-PfbNetworkAccessPolicy',
        'Get-PfbNetworkAccessPolicyMember',
        'Get-PfbNetworkAccessRule',
        'Get-PfbNetworkConnectionStatistics',
        'Get-PfbNetworkInterface',
        'Get-PfbNetworkInterfaceConnector',
        'Get-PfbNetworkInterfaceConnectorPerformance',
        'Get-PfbNetworkInterfaceConnectorSettings',
        'Get-PfbNetworkInterfaceNeighbor',
        'Get-PfbNetworkInterfaceTlsPolicy',
        'Get-PfbNfsExportPolicy',
        'Get-PfbNfsExportRule',
        'Get-PfbNode',
        'Get-PfbNodeGroup',
        'Get-PfbNodeGroupNode',
        'Get-PfbNodeGroupUse',
        'Get-PfbObjectStoreAccessKey',
        'Get-PfbObjectStoreAccessPolicy',
        'Get-PfbObjectStoreAccessPolicyAction',
        'Get-PfbObjectStoreAccessPolicyRole',
        'Get-PfbObjectStoreAccessPolicyRule',
        'Get-PfbObjectStoreAccessPolicyUser',
        'Get-PfbObjectStoreAccount',
        'Get-PfbObjectStoreAccountExport',
        'Get-PfbObjectStoreRemoteCredential',
        'Get-PfbObjectStoreRole',
        'Get-PfbObjectStoreRoleAccessPolicy',
        'Get-PfbObjectStoreTrustPolicy',
        'Get-PfbObjectStoreTrustPolicyRule',
        'Get-PfbObjectStoreUser',
        'Get-PfbObjectStoreUserAccessPolicy',
        'Get-PfbObjectStoreVirtualHost',
        'Get-PfbOidcIdp',
        'Get-PfbOpenFile',
        'Get-PfbPasswordPolicy',
        'Get-PfbPolicy',
        'Get-PfbPolicyAll',
        'Get-PfbPolicyAllMember',
        'Get-PfbPolicyFileSystem',
        'Get-PfbPolicyFileSystemReplicaLink',
        'Get-PfbPolicyFileSystemSnapshot',
        'Get-PfbPolicyMember',
        'Get-PfbPublicKey',
        'Get-PfbPublicKeyUse',
        'Get-PfbQosPolicy',
        'Get-PfbQosPolicyBucket',
        'Get-PfbQosPolicyFileSystem',
        'Get-PfbQosPolicyMember',
        'Get-PfbQuotaGroup',
        'Get-PfbQuotaSettings',
        'Get-PfbQuotaUser',
        'Get-PfbRapidDataLocking',
        'Get-PfbRealm',
        'Get-PfbRealmDefaults',
        'Get-PfbRealmSpace',
        'Get-PfbRealmStorageClass',
        'Get-PfbRemoteArray',
        'Get-PfbResiliencyGroup',
        'Get-PfbResourceAccess',
        'Get-PfbRole',
        'Get-PfbS3ExportPolicy',
        'Get-PfbS3ExportRule',
        'Get-PfbSaml2Idp',
        'Get-PfbServer',
        'Get-PfbSession',
        'Get-PfbSmbClientPolicy',
        'Get-PfbSmbClientRule',
        'Get-PfbSmbSharePolicy',
        'Get-PfbSmbShareRule',
        'Get-PfbSmtp',
        'Get-PfbSmtpServer',
        'Get-PfbSnmpAgent',
        'Get-PfbSnmpAgentMib',
        'Get-PfbSnmpManager',
        'Get-PfbSoftwareCheck',
        'Get-PfbSshCaPolicy',
        'Get-PfbSshCaPolicyAdmin',
        'Get-PfbSshCaPolicyArray',
        'Get-PfbSshCaPolicyMember',
        'Get-PfbStorageClassTieringPolicy',
        'Get-PfbStorageClassTieringPolicyMember',
        'Get-PfbSubnet',
        'Get-PfbSupport',
        'Get-PfbSupportDiagnostics',
        'Get-PfbSupportDiagnosticsDetails',
        'Get-PfbSupportVerificationKey',
        'Get-PfbSyslogServer',
        'Get-PfbSyslogServerSettings',
        'Get-PfbTarget',
        'Get-PfbTargetPerformanceReplication',
        'Get-PfbTlsPolicy',
        'Get-PfbTlsPolicyMember',
        'Get-PfbUsageGroup',
        'Get-PfbUsageUser',
        'Get-PfbWormPolicy',
        'Get-PfbWormPolicyMember',
        'Invoke-PfbNetworkPing',
        'Invoke-PfbNetworkTrace',
        'New-PfbActiveDirectory',
        'New-PfbAdminManagementAccessPolicy',
        'New-PfbAdminSshCaPolicy',
        'New-PfbAlertWatcher',
        'New-PfbApiClient',
        'New-PfbApiToken',
        'New-PfbArrayConnection',
        'New-PfbArrayConnectionKey',
        'New-PfbArrayErasure',
        'New-PfbArrayFactoryResetToken',
        'New-PfbArraySshCaPolicy',
        'New-PfbAuditFileSystemPolicy',
        'New-PfbAuditFileSystemPolicyMember',
        'New-PfbAuditObjectStorePolicy',
        'New-PfbAuditObjectStorePolicyMember',
        'New-PfbBucket',
        'New-PfbBucketAccessPolicy',
        'New-PfbBucketAccessPolicyRule',
        'New-PfbBucketAuditFilter',
        'New-PfbBucketCorsPolicy',
        'New-PfbBucketCorsPolicyRule',
        'New-PfbCertificate',
        'New-PfbCertificateCertificateGroup',
        'New-PfbCertificateGroup',
        'New-PfbCertificateSigningRequest',
        'New-PfbDirectoryServiceRole',
        'New-PfbDirectoryServiceRoleManagementPolicy',
        'New-PfbDns',
        'New-PfbFileSystem',
        'New-PfbFileSystemAuditPolicy',
        'New-PfbFileSystemExport',
        'New-PfbFileSystemPolicy',
        'New-PfbFileSystemReplicaLink',
        'New-PfbFileSystemReplicaLinkPolicy',
        'New-PfbFileSystemSnapshot',
        'New-PfbFileSystemSnapshotPolicy',
        'New-PfbFleet',
        'New-PfbFleetKey',
        'New-PfbFleetMember',
        'New-PfbKeytab',
        'New-PfbKeytabUpload',
        'New-PfbLag',
        'New-PfbLegalHold',
        'New-PfbLegalHoldEntity',
        'New-PfbLifecycleRule',
        'New-PfbLogTargetFileSystem',
        'New-PfbLogTargetObjectStore',
        'New-PfbMaintenanceWindow',
        'New-PfbManagementAccessPolicy',
        'New-PfbManagementAccessPolicyAdmin',
        'New-PfbManagementAccessPolicyDirectoryRole',
        'New-PfbNetworkAccessPolicy',
        'New-PfbNetworkAccessRule',
        'New-PfbNetworkInterface',
        'New-PfbNetworkInterfaceTlsPolicy',
        'New-PfbNfsExportPolicy',
        'New-PfbNfsExportRule',
        'New-PfbNlmReclamation',
        'New-PfbNodeGroup',
        'New-PfbNodeGroupNode',
        'New-PfbObjectStoreAccessKey',
        'New-PfbObjectStoreAccessPolicy',
        'New-PfbObjectStoreAccessPolicyRole',
        'New-PfbObjectStoreAccessPolicyRule',
        'New-PfbObjectStoreAccessPolicyUser',
        'New-PfbObjectStoreAccount',
        'New-PfbObjectStoreAccountExport',
        'New-PfbObjectStoreRemoteCredential',
        'New-PfbObjectStoreRole',
        'New-PfbObjectStoreRoleAccessPolicy',
        'New-PfbObjectStoreTrustPolicyRule',
        'New-PfbObjectStoreUser',
        'New-PfbObjectStoreUserAccessPolicy',
        'New-PfbObjectStoreVirtualHost',
        'New-PfbOidcIdp',
        'New-PfbPolicy',
        'New-PfbPolicyFileSystemReplicaLink',
        'New-PfbPolicyMember',
        'New-PfbPublicKey',
        'New-PfbQosPolicy',
        'New-PfbQosPolicyMember',
        'New-PfbQuotaGroup',
        'New-PfbQuotaUser',
        'New-PfbRapidDataLockingRotation',
        'New-PfbRealm',
        'New-PfbS3ExportPolicy',
        'New-PfbS3ExportRule',
        'New-PfbSaml2Idp',
        'New-PfbServer',
        'New-PfbSmbClientPolicy',
        'New-PfbSmbClientRule',
        'New-PfbSmbSharePolicy',
        'New-PfbSmbShareRule',
        'New-PfbSnmpManager',
        'New-PfbSoftwareCheck',
        'New-PfbSshCaPolicy',
        'New-PfbSshCaPolicyAdmin',
        'New-PfbSshCaPolicyArray',
        'New-PfbStorageClassTieringPolicy',
        'New-PfbSubnet',
        'New-PfbSupportDiagnostics',
        'New-PfbSyslogServer',
        'New-PfbTarget',
        'New-PfbTlsPolicy',
        'New-PfbWormPolicy',
        'Remove-PfbActiveDirectory',
        'Remove-PfbAdminCache',
        'Remove-PfbAdminManagementAccessPolicy',
        'Remove-PfbAdminSshCaPolicy',
        'Remove-PfbAlertWatcher',
        'Remove-PfbApiClient',
        'Remove-PfbApiToken',
        'Remove-PfbArrayConnection',
        'Remove-PfbArrayErasure',
        'Remove-PfbArrayFactoryResetToken',
        'Remove-PfbArraySshCaPolicy',
        'Remove-PfbAuditFileSystemPolicy',
        'Remove-PfbAuditFileSystemPolicyMember',
        'Remove-PfbAuditObjectStorePolicy',
        'Remove-PfbAuditObjectStorePolicyMember',
        'Remove-PfbBucket',
        'Remove-PfbBucketAccessPolicy',
        'Remove-PfbBucketAccessPolicyRule',
        'Remove-PfbBucketAuditFilter',
        'Remove-PfbBucketCorsPolicy',
        'Remove-PfbBucketCorsPolicyRule',
        'Remove-PfbCertificate',
        'Remove-PfbCertificateCertificateGroup',
        'Remove-PfbCertificateGroup',
        'Remove-PfbDirectoryServiceRole',
        'Remove-PfbDirectoryServiceRoleManagementPolicy',
        'Remove-PfbDns',
        'Remove-PfbFileLock',
        'Remove-PfbFileSystem',
        'Remove-PfbFileSystemAuditPolicy',
        'Remove-PfbFileSystemExport',
        'Remove-PfbFileSystemPolicy',
        'Remove-PfbFileSystemReplicaLink',
        'Remove-PfbFileSystemReplicaLinkPolicy',
        'Remove-PfbFileSystemSession',
        'Remove-PfbFileSystemSnapshot',
        'Remove-PfbFileSystemSnapshotPolicy',
        'Remove-PfbFileSystemSnapshotTransfer',
        'Remove-PfbFleet',
        'Remove-PfbFleetMember',
        'Remove-PfbKeytab',
        'Remove-PfbLag',
        'Remove-PfbLegalHold',
        'Remove-PfbLifecycleRule',
        'Remove-PfbLogTargetFileSystem',
        'Remove-PfbLogTargetObjectStore',
        'Remove-PfbMaintenanceWindow',
        'Remove-PfbManagementAccessPolicy',
        'Remove-PfbManagementAccessPolicyAdmin',
        'Remove-PfbManagementAccessPolicyDirectoryRole',
        'Remove-PfbNetworkAccessPolicy',
        'Remove-PfbNetworkAccessRule',
        'Remove-PfbNetworkInterface',
        'Remove-PfbNetworkInterfaceTlsPolicy',
        'Remove-PfbNfsExportPolicy',
        'Remove-PfbNfsExportRule',
        'Remove-PfbNodeGroup',
        'Remove-PfbNodeGroupNode',
        'Remove-PfbObjectStoreAccessKey',
        'Remove-PfbObjectStoreAccessPolicy',
        'Remove-PfbObjectStoreAccessPolicyRole',
        'Remove-PfbObjectStoreAccessPolicyRule',
        'Remove-PfbObjectStoreAccessPolicyUser',
        'Remove-PfbObjectStoreAccount',
        'Remove-PfbObjectStoreAccountExport',
        'Remove-PfbObjectStoreRemoteCredential',
        'Remove-PfbObjectStoreRole',
        'Remove-PfbObjectStoreRoleAccessPolicy',
        'Remove-PfbObjectStoreTrustPolicyRule',
        'Remove-PfbObjectStoreUser',
        'Remove-PfbObjectStoreUserAccessPolicy',
        'Remove-PfbObjectStoreVirtualHost',
        'Remove-PfbOidcIdp',
        'Remove-PfbOpenFile',
        'Remove-PfbPolicy',
        'Remove-PfbPolicyFileSystemReplicaLink',
        'Remove-PfbPolicyMember',
        'Remove-PfbPublicKey',
        'Remove-PfbQosPolicy',
        'Remove-PfbQosPolicyMember',
        'Remove-PfbQuotaGroup',
        'Remove-PfbQuotaUser',
        'Remove-PfbRealm',
        'Remove-PfbResourceAccess',
        'Remove-PfbS3ExportPolicy',
        'Remove-PfbS3ExportRule',
        'Remove-PfbSaml2Idp',
        'Remove-PfbServer',
        'Remove-PfbSession',
        'Remove-PfbSmbClientPolicy',
        'Remove-PfbSmbClientRule',
        'Remove-PfbSmbSharePolicy',
        'Remove-PfbSmbShareRule',
        'Remove-PfbSnmpManager',
        'Remove-PfbSshCaPolicy',
        'Remove-PfbSshCaPolicyAdmin',
        'Remove-PfbSshCaPolicyArray',
        'Remove-PfbStorageClassTieringPolicy',
        'Remove-PfbSubnet',
        'Remove-PfbSyslogServer',
        'Remove-PfbTarget',
        'Remove-PfbTlsPolicy',
        'Remove-PfbWormPolicy',
        'Set-PfbCredential',
        'Test-PfbActiveDirectory',
        'Test-PfbAlertWatcher',
        'Test-PfbConnection',
        'Test-PfbDirectoryService',
        'Test-PfbKmip',
        'Test-PfbRapidDataLocking',
        'Test-PfbSaml2Idp',
        'Test-PfbSnmpManager',
        'Test-PfbSupport',
        'Test-PfbSyslogServer',
        'Update-PfbActiveDirectory',
        'Update-PfbAdmin',
        'Update-PfbAdminSetting',
        'Update-PfbAlert',
        'Update-PfbAlertWatcher',
        'Update-PfbApiClient',
        'Update-PfbArray',
        'Update-PfbArrayConnection',
        'Update-PfbArrayErasure',
        'Update-PfbArrayEula',
        'Update-PfbAsyncLog',
        'Update-PfbAuditFileSystemPolicy',
        'Update-PfbAuditObjectStorePolicy',
        'Update-PfbBucket',
        'Update-PfbBucketAuditFilter',
        'Update-PfbCertificate',
        'Update-PfbDirectoryService',
        'Update-PfbDirectoryServiceRole',
        'Update-PfbDns',
        'Update-PfbFileSystem',
        'Update-PfbFileSystemExport',
        'Update-PfbFleet',
        'Update-PfbHardware',
        'Update-PfbHardwareConnector',
        'Update-PfbKmip',
        'Update-PfbLag',
        'Update-PfbLegalHold',
        'Update-PfbLegalHoldEntity',
        'Update-PfbLifecycleRule',
        'Update-PfbLogTargetFileSystem',
        'Update-PfbLogTargetObjectStore',
        'Update-PfbManagementAccessPolicy',
        'Update-PfbNetworkAccessPolicy',
        'Update-PfbNetworkAccessRule',
        'Update-PfbNetworkInterface',
        'Update-PfbNetworkInterfaceConnector',
        'Update-PfbNfsExportPolicy',
        'Update-PfbNfsExportRule',
        'Update-PfbNode',
        'Update-PfbNodeGroup',
        'Update-PfbObjectStoreAccessPolicyRule',
        'Update-PfbObjectStoreAccountExport',
        'Update-PfbObjectStoreRemoteCredential',
        'Update-PfbObjectStoreRole',
        'Update-PfbObjectStoreTrustPolicyRule',
        'Update-PfbObjectStoreVirtualHost',
        'Update-PfbOidcIdp',
        'Update-PfbPasswordPolicy',
        'Update-PfbPolicy',
        'Update-PfbQosPolicy',
        'Update-PfbQuotaGroup',
        'Update-PfbQuotaSettings',
        'Update-PfbQuotaUser',
        'Update-PfbRapidDataLocking',
        'Update-PfbRealm',
        'Update-PfbRealmDefaults',
        'Update-PfbS3ExportPolicy',
        'Update-PfbS3ExportRule',
        'Update-PfbSaml2Idp',
        'Update-PfbServer',
        'Update-PfbSmbClientPolicy',
        'Update-PfbSmbClientRule',
        'Update-PfbSmbSharePolicy',
        'Update-PfbSmbShareRule',
        'Update-PfbSmtp',
        'Update-PfbSnmpAgent',
        'Update-PfbSnmpManager',
        'Update-PfbSshCaPolicy',
        'Update-PfbStorageClassTieringPolicy',
        'Update-PfbSubnet',
        'Update-PfbSupport',
        'Update-PfbSupportVerificationKey',
        'Update-PfbSyslogServer',
        'Update-PfbSyslogServerSettings',
        'Update-PfbTarget',
        'Update-PfbTlsPolicy',
        'Update-PfbWormPolicy',
        # Workloads (v2.0.4)
        'Get-PfbWorkload',
        'New-PfbWorkload',
        'Update-PfbWorkload',
        'Remove-PfbWorkload',
        'Get-PfbWorkloadPlacementRecommendation',
        'New-PfbWorkloadPlacementRecommendation',
        'Get-PfbWorkloadTag',
        'Set-PfbWorkloadTag',
        'Remove-PfbWorkloadTag',
        # Workload presets (v2.0.4)
        'Get-PfbPresetWorkload',
        'New-PfbPresetWorkload',
        'Set-PfbPresetWorkload',
        'Update-PfbPresetWorkload',
        'Remove-PfbPresetWorkload',
        # Data eviction policies (v2.0.4)
        'Get-PfbDataEvictionPolicy',
        'New-PfbDataEvictionPolicy',
        'Update-PfbDataEvictionPolicy',
        'Remove-PfbDataEvictionPolicy',
        'Get-PfbDataEvictionPolicyFileSystem',
        'Add-PfbDataEvictionPolicyFileSystem',
        'Remove-PfbDataEvictionPolicyFileSystem',
        'Get-PfbDataEvictionPolicyMember'
    )
    CmdletsToExport   = @()
    VariablesToExport  = @()
    AliasesToExport    = @()

    PrivateData = @{
        PSData = @{
            Tags         = @('PureStorage', 'FlashBlade', 'Storage', 'REST', 'API', 'S3', 'NFS', 'SMB', 'FlashBlade2')
            ProjectUri   = 'https://github.com/PureStorage-OpenConnect/flashblade-powershell-toolkit'
            LicenseUri   = 'https://github.com/PureStorage-OpenConnect/flashblade-powershell-toolkit/blob/master/LICENSE'
            ReleaseNotes = @'
v2.0.3 - Real-AD test suite + HTML report generator. See CHANGELOG.md.
  Added:
  - Tests/SmbShareScript.AD.Tests.ps1: 8 live tests with a real AD identity as
    lockdown principal; verifies NTFS via icacls actually lands on the share.
  - Tests/Generate-Reports.ps1: produces a self-contained HTML bundle
    (index + per-suite HTML + NUnit XML + every markdown doc rendered).
  Verified live: 29/29 Pester tests pass in ~32s.

v2.0.2 - SMB share lockdown script + Update-PfbFileSystem expansion. See CHANGELOG.md.
  Added:
  - examples/New-LockdownFlashBladeShare.ps1 (lockdown -> NTFS -> production-flip)
  - Tests/SmbShareScript.Tests.ps1 (8 live tests against the lab)
  - Tests/API_COVERAGE.md (spec gap analysis, ~84% coverage)
  - Tests/TEST_REPORT.md

  Changed:
  - Update-PfbFileSystem: typed -SmbSharePolicy, -SmbClientPolicy, -NfsExportPolicy
    parameters (no more hashtable-only flipping for the lockdown workflow).

  Fixed:
  - Compound filter idempotency check on /smb-share-policies/rules: FB returns
    a count-only stub for "policy.name='x' and principal='y'". Single-clause
    filter + client-side narrow is the workaround.

  Verified:
  - 21/21 Pester tests pass live against Purity//FB 4.8.2 / API 2.26 in ~28s

v2.0.1 - Posh-SSH dependency removed. See CHANGELOG.md for full diff.
  Removed:
  - Posh-SSH dependency entirely. Username/password auth now uses native REST 2.x /api/login.

  Fixed:
  - New-PfbNetworkInterface: removed read-only `subnet` field from POST body (was returning "Invalid body parameter").
  - New-PfbFileSystem: switch parameter name collision ($smb/$Smb) caused SwitchParameter cast errors.
  - New-PfbFileSystemSnapshot: -Suffix was sent as query param, now correctly in request body.

  Added:
  - New-PfbFileSystemReplicaLink / Remove-PfbFileSystemReplicaLink (gap in v2.0.0).
  - New-PfbFileSystemSnapshot -Send / -Targets for one-shot manual replication.
  - Tests/SmbWorkflow.E2E.Tests.ps1: end-to-end SMB workflow suite including cross-array replication.
  - Tests/SMB_SHARE_WORKFLOW.md: per-operation cmdlet mapping reference.

  Changed:
  - Connect-PfbArray default display hides ApiToken / AuthToken / BearerToken.
  - Invoke-PfbApiRequest emits Write-Verbose for every endpoint hit.
  - New-PfbFileSystem / New-PfbServer / Update-PfbServer / New-PfbNetworkInterface: typed parameters with mutually exclusive -Attributes parameter set.
  - Remove-PfbFileSystem: added -DeleteLinkOnEradication for FSes that participate in a replica link.
  - Remove-Pfb{FileSystem,Bucket,Server,ObjectStoreUser,ObjectStoreAccount,Policy}: reject -Name '*' / '?' / empty at parameter binding.

v2.0.0 - Complete rewrite targeting FlashBlade REST API 2.x.
  Breaking changes from v1.x (PureFBModule):
  - New module name: PureStorageFlashBladePowerShell (was PureFBModule)
  - Session-based connection model: Connect-PfbArray / Disconnect-PfbArray
  - REST API 2.x only (1.x is no longer targeted)
  - Cmdlet naming follows Verb-PfbNoun pattern with Get/New/Update/Remove verbs

  New in v2.0.0:
  - 493 cmdlets covering 218 FlashBlade REST API 2.x endpoints
  - Connect-PfbArray mirrors the FlashArray Connect-Pfa2Array experience
  - Four authentication methods: ApiToken, Username/Password, PSCredential, Certificate (OAuth2/JWT)
  - Native REST 2.x /api/login for username/password (no external SSH module required)
  - Connection object exposes .HttpEndpoint, .Username, .ApiToken, .RestApiVersion (Pfa2-compatible)
  - Modular architecture: Public/ and Private/ function layout
  - PowerShell 5.1+ compatible
'@
        }
    }
}
